# Generated by Django 5.2.17 on 2026-08-31 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('EXATAS', 'Exatas'), ('HUMANAS', 'Humanas'), ('BIOLOGICAS', 'Biológicas')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, help_text='Rua, Número e Bairro', max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('meio_de_transporte', models.CharField(choices=[('PARTICULAR', 'Carro / Moto'), ('PUBLICO', 'Transporte Público'), ('OUTRO', 'A pé / Outro')], default='PARTICULAR', max_length=20)),
                ('limite_aulas', models.PositiveIntegerField(default=5, help_text='Limite de aulas por dia')),
                ('observacao', models.TextField(blank=True, help_text='Informações personalizadas para consulta na montagem da grade', null=True)),
                ('disciplinas', models.ManyToManyField(related_name='professores', to='grade.disciplina')),
                ('parente_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.professor', verbose_name='Parente (Mesmo turno/unidade)')),
                ('unidade_oficial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores_oficiais', to='grade.unidade')),
                ('unidades_permitidas', models.ManyToManyField(related_name='professores_permitidos', to='grade.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('disponivel_manha', models.BooleanField(default=False)),
                ('disponivel_tarde', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='grade.professor')),
            ],
        ),
        migrations.CreateModel(
            name='MatrizDistancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_minutos', models.PositiveIntegerField(help_text='Tempo médio de deslocamento em minutos')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distancias_destino', to='grade.unidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distancias_origem', to='grade.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.horarioaula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.professor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.unidade')),
            ],
        ),
    ]
