# Generated by Django 6.0.5 on 2026-05-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('EXATAS', 'Exatas'), ('HUMANAS', 'Humanas'), ('BIOLOGICAS', 'Biológicas')], default='HUMANAS', max_length=20)),
                ('meio_de_transporte', models.CharField(choices=[('PARTICULAR', 'Carro / Moto'), ('PUBLICO', 'Transporte Público'), ('OUTRO', 'A pé / Outro')], default='PARTICULAR', max_length=20)),
                ('conjuge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.professor', verbose_name='Casado(a) com')),
                ('unidade_oficial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores_oficiais', to='grade.unidade')),
                ('unidades_permitidas', models.ManyToManyField(related_name='professores_permitidos', to='grade.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('disponivel_manha', models.BooleanField(default=False, verbose_name='Disponível de Manhã')),
                ('disponivel_tarde', models.BooleanField(default=False, verbose_name='Disponível de Tarde')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='grade.professor')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.horarioaula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.professor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.unidade')),
            ],
        ),
    ]
