# Generated by Django 5.2.17 on 2026-09-13 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaograde',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que autorizou a exceção', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='eh_excecao_area_acumulo',
            field=models.BooleanField(default=False, help_text='Permitir acúmulo de aulas da mesma área'),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='eh_excecao_deslocamento',
            field=models.BooleanField(default=False, help_text='Autorizar deslocamento com tempo insuficiente'),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='eh_excecao_horario',
            field=models.BooleanField(default=False, help_text='Permitir duplicação de horário (raro)'),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='eh_excecao_limite_aulas',
            field=models.BooleanField(default=False, help_text='Autorizar exceção de limite de aulas/dia'),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='motivo_excecao_area_acumulo',
            field=models.CharField(blank=True, help_text='Justificativa para exceção de acúmulo de área', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='motivo_excecao_deslocamento',
            field=models.CharField(blank=True, help_text='Justificativa para exceção de deslocamento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='motivo_excecao_horario',
            field=models.CharField(blank=True, help_text='Justificativa para exceção de horário', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alocacaograde',
            name='motivo_excecao_limite',
            field=models.CharField(blank=True, help_text='Justificativa para exceção de limite', max_length=200, null=True),
        ),
    ]
